name: svbias
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.26
  - pandas>=2.2
  - scikit-learn>=1.4
  - pyarrow>=15
  - scipy>=1.11
  - statsmodels>=0.14
  - tqdm>=4.66
  - pip:
      - bedparse==0.2.3

